### ISSUE TITLE
login function incomplete

### ISSUE THREAD

**Issue by dxts** [rushatgabhane/Jaba-Jaba-Hospital#1]
Who will check whether the username and password entered are correct or not
[https://github.com/rushatgabhane/Jaba-Jaba-Hospital/blob/master/login.cpp](url)

**Comment by MrFuriousFury** [comment]
Still working on that

_Sent from my HUAWEI MHA-L29 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by amalpavithran** [comment]
@dixitS05 still working on that

_Sent from my HUAWEI MHA-L29 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
